
CREATE USER 'nodejs'@'localhost' IDENTIFIED BY '***';GRANT ALL PRIVILEGES ON *.* TO 'nodejs'@'localhost' IDENTIFIED BY '***' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

